# Generated by Django 3.1.6 on 2021-02-24 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210224_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentartikel',
            old_name='artikel',
            new_name='title',
        ),
    ]
