# Generated by Django 3.1.6 on 2021-02-24 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210224_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentartikel',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.artikel'),
        ),
    ]
